---
title: "0.2_monthly_chla_download"
author: "mz"
format: html
editor: source
---

## Libraries

load the packages needed for downloading the data

```{r}


library(RCMEMS)
library(raster)
```

load credentials


```{r}
# read cred file ingoring row names


cred <- read.csv(here::here('data/credentials.csv'), sep = ";")

user <- cred$user
pss <- cred$pss

```


(raw) Script to download files

cmems_obs-oc_arc_bgc-plankton_nrt_l3-multi-1km_P1D 

```{r}
scriptGEN <- 'python -m motuclient --motu https://nrt.cmems-du.eu/motu-web/Motu --service-id OCEANCOLOUR_ARC_BGC_L3_MY_009_123-TDS --product-id cmems_obs-oc_arc_bgc-plankton_my_l3-multi-1km_P1D --longitude-min 8.108733966600544 --longitude-max 29.696539876169563 --latitude-min 75.00125112781981 --latitude-max 81.44324966188955 --date-min "2022-06-04 00:00:00" --date-max "2022-06-05 23:59:59" --variable CHL --out-dir <OUTPUT_DIRECTORY> --out-name <OUTPUT_FILENAME> --user <USERNAME> --pwd <PASSWORD> '
```

adjust the script with credentials and other relevant infos

```{r}
cfg <- parse.CMEMS.script(scriptGEN)
cfg2 <- update(cfg,user= user, pwd =pss, out.dir = "data/")
#cfg2
```

## test product

Start the test with two days


```{r}




      date.min <- paste0(2022, "-0", 7, "-01 00:00:00")
      date.max <- paste0(2022, "-0", 7, "-02 00:00:00")
      out.name <- paste0("test_download_", 202205, ".nc")
      longMax <- "50"
      longMin <- "-10"
      latMax <- "85"
      latMin <- "72"
      out.dir <- "data/monthly_from_daily"
      
      
      
      cfg3 <- update(cfg2, 
                     date.min = date.min,
                     date.max = date.max,
                     out.name = out.name,
                     longitude.max = longMax,
                     longitude.min = longMin,
                     latitude.max = latMax,
                     latitude.min = latMin,
                     out.dir = out.dir)
        
      
      
      CMEMS.download(cfg3)
      
 

```


the dataset start from sepotember 2022


we need to check if it is available as multiyear product

```{r}

```

